### ISSUE TITLE
Naming improvements

### ISSUE THREAD

**Issue by ktraunmueller** [runtastic/Matrioska#14]
Hi all,

I have some suggestions on naming.

### Meaning of "view"

The term "view" is currently used for two different things.

- There's an enum case in `Component` called `.view`:

```
public indirect enum Component {

    public typealias ViewBuilder = (_ meta: ComponentMeta?) -> UIViewController?
    
    case view(builder: ViewBuilder, meta: ComponentMeta?)
```

So, a `.view` is a certain type of component.

- There's also a function type called `ViewBuilder`. This doesn't build `.view` components, however, it builds _view controllers_, something entirely different.

Similarly, there are function types `WrapperBuilder` and `ClusterBuilder` that don't produce `.wrapper` or `.cluster` components, either, they all produce view controllers.

```
public typealias WrapperBuilder = (
        _ child: Component,
        _ meta: ComponentMeta?
        ) -> UIViewController?
```

I'd suggest using the term "view" for _view controllers_ solely and
- rename the function types `WrapperBuilder` and `ClusterBuilder` to `WrapperViewBuilder` and `ClusterViewBuilder`, respectively
- find a more distinguished name for the `.view` Component (to not confuse this with view controllers)
- rename the function type `ViewBuilder` according to the new component name

Maybe rename `.view` to `.standalone`, e.g.

```
public indirect enum Component {

    public typealias StandaloneViewBuilder = (_ meta: ComponentMeta?) -> UIViewController?
    
    public typealias WrapperViewBuilder = (
        _ child: Component,
        _ meta: ComponentMeta?
        ) -> UIViewController?
    
    public typealias ClusterViewBuilder = (
        _ children: [Component],
        _ meta: ComponentMeta?
        ) -> UIViewController?

    case standalone(builder: StandaloneViewBuilder, meta: ComponentMeta?)
    case wrapper(builder: WrapperViewBuilder, child: Component, meta: ComponentMeta?)
    case cluster(builder: ClusterViewBuilder, children: [Component], meta: ComponentMeta?)
```

###  (view) `builder` parameter names

And in the course of this maybe also rename the `builder` parameters in the `Component` enum cases to `viewBuilder`, to make it clear above any doubt (on the call site) what kind of function is expected here.

```
public indirect enum Component {
    case standalone(viewBuilder: StandaloneViewBuilder, meta: ComponentMeta?)
    case wrapper(viewBuilder: WrapperViewBuilder, child: Component, meta: ComponentMeta?)
    case cluster(viewBuilder: ClusterViewBuilder, children: [Component], meta: ComponentMeta?)
```

This should help discriminate from the other use of the `builder` argument label, which is used for registering `Component` builders in component factories (see below).

### Signature of `register()` methods

Lastly, change the order of arguments of the `register()` methods in `JSONFactory` from
```
func register(with type: String, factoryBuilder: @escaping ViewFactoryBuilder)
```
to
```
func register(builder: @escaping StandaloneBuilder, forType type: String)
```
so that
```
jsonFactory.register(with: "tabbar", factoryBuilder: tabBarBuilder)
```
becomes
```
jsonFactory.register(builder: tabBarBuilder, forType: "tabbar")
```
at the call site.

**Comment by mathiasAichinger** [comment]
I don't like the term standalone. any other suggestions?

**Comment by AndreasThenn** [comment]
single, childless, leaf, baby ...? But I am also ok with standalone ;) - Overall I really like the improvements @ktraunmueller

**Comment by ktraunmueller** [comment]
"single" would be fine with me (contrasts nicely with "cluster"), or maybe "individual".

**Comment by ktraunmueller** [comment]
Two more suggestions:

### Replace "factory" with "builder" everywhere

Right now, the `JSONFactory` uses both terms "factory" and "builder" for component builders:

```
var wrapperFactories: [String: WrapperBuilder] = [:]
```

This declaration should be consistent with respect to naming, i.e.

```
var wrapperBuilders: [String: WrapperBuilder] = [:]
```

### Change factory method naming to start with "make"

The `JSONFactory` has methods like

```
func component(from json: JSONObject) throws -> Component?
func component(fromStructure json: JSONObject) throws -> Component?
func component(from type: String, meta: JSONObject?, children: [Component]) -> Component? 
func rule(from object: Any, using factories: [String: JSONFactory.RuleBuilder]) -> Rule?
```

For one, these method names should probably start with a verb (indicating the side-effect), so that you can use the term "component" for the result of the call, e.g.

```
let component = makeComponent(type: type, meta: meta, children: children)
```

Also, the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/#naming) suggest to: 
-  _"Begin names of factory methods with “make”"_ and 
- _"Initializer and factory method calls should form a phrase that does not include the first argument"_

I'd suggest changing these methods to 

```
func makeComponent(json: JSONObject) throws -> Component?
func makeComponent(structure json: JSONObject) throws -> Component? 
func makeComponent(type: String, meta: JSONObject?, children: [Component]) -> Component?
func makeRule(object: Any, builders: [String: JSONFactory.RuleBuilder]) -> Rule?
```

**Comment by mathiasAichinger** [comment]
@MP0w @joanromano Any input from your side?

**Comment by MP0w** [comment]
Not a fan of `standalone` maybe something different.
Will try explain the reasoning about the current naming:
`Component` is a model that represents a UI component. Matrioska has 3 types of UI components views, wrapper(views) and cluster(views). The fact that they produce a UIVieeCotroller is an implementation detail, they could theoretically produce UIViews, CALayers or different stuff on Android. 
Even if a Component can produce ViewControllers (which are views), Component.view() is a Component that represents (and can build) a view.
I think that Component.view express in a better way what it is compared to Component.standalone().
I would see them as view, viewWrapper and viewsCluster

**Comment by joanromano** [comment]
Renaming `.view` to something different is an extremely important renaming. The reasons for the change are mainly confussion as I here, and thus I wouldn't change it right now since this is not a general feeling afaik.

I would be ok to change the builder names to something more expressive if you want. Also agree with the change on `register` method with the param order.

**Comment by joanromano** [comment]
Regarding factories: the snippet is wrong, the factories contain factory builders not just builders, e.g:

`wrapperFactory: [String: WrapperFactoryBuilder]`

And so I would leave them as they are.

I am fine with the addition of `make` in the other methods though why removing the `from` prefix? And also those are private methods anyway.

**Comment by ktraunmueller** [comment]
> Even if a Component can produce ViewControllers (which are views), Component.view() is a Component that represents (and can build) a view.

You're highlighting my point: the term "view" is used for two unrelated things: 1) a certain type of component and 2) view controllers.

> The fact that they produce a UIViewCotroller is an implementation detail.

Not really, it's ingrained in the interface of `Component`. All the view builders function types (used for associated values) have `UIViewController` as their return type.

> the factories contain factory builders not just builders

What you refer to as "factory builders" looks like component builders (that return a `Component`) to me, correct? And what you refer to as "builders" are view builders (that return a `UIViewController`), right?

**Comment by joanromano** [comment]
@ktraunmueller yep, but there is only `ViewFactoryBuilder`, `WrapperFactoryBuilder `... and so on, right?

**Comment by AndreasThenn** [comment]
Since the PR was merged, I would close this issue.
But there is one thing left, I want to suggest:
Rename `axis` to `orientation` for the stack - I think this fits better and our colleagues on Android are already using that name. I will add this via PullRequest, if you're fine with it.

**Comment by joanromano** [comment]
Fine for me.

btw for the next times, an issue can be closed from a PR https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by ktraunmueller** [comment]
Nice; thanks for pointing out.
