### ISSUE TITLE
Meta handling

### ISSUE THREAD

**Issue by bassemawny** [runtastic/Matrioska#16]
The current state in Matrioska, each `clusterView` supports a defined set of `meta` attributes that are handled in the corresponding `clusterView`'s factory. 
There are some drawbacks to this approach:
- The generic `clusterViews` (such as the `stackClusterView` and the `tabbarClusterView`) are not really open for extension like having other attributes than the ones hard-coded in the factories.
- When implementing new `clusterViews` that will be used for different apps, they will be responsible for having to handle all the possible `meta` values from all the different JSONs of all apps.
- In the previous case also, the app will have no influence on how to handle the different `meta` but this responsibility will rather be shifted to the library/pod to which the `clusterView` belongs.

So my proposal is creating a new `metaHandler` interface that contains a method like:
`applyMeta (JSONObject meta, ClusterView clusterView)`

Each factory would then have  a `metaHandler` local variable which should be implemented by the app and passed to the factory through the constructor when first registering the factory. 

This approach would have the benefits such as: 
- The flexibility of adding application specific attributes as needed.
- The re-usability of `clusterViews` with different properties.

**Comment by mathiasAichinger** [comment]
@bassemawny I like the idea, but I need to see how it feels implementing such handlers. I will try it out and create a PR on weekend or next week.

**Comment by mathiasAichinger** [comment]
@bassemawny I have quickly checked this and it would require some deeper changes. I would suggest to do it at a later point and for the moment stick with the current solution.

**Comment by MP0w** [comment]
+1 seems good to extend stdlib components but should be optional and nice to use

**Comment by MP0w** [comment]
However it's hard to extend a component without knowing about the view, if ou know too much about the underlying view then the point of component should is gone

**Comment by ChristianOrgler** [comment]
I agree, I close this for now and we may wanna come back later to this idea.
