### ISSUE TITLE
Vision of the project

### ISSUE THREAD

**Issue by ChristianOrgler** [runtastic/Matrioska#20]
As we come into the discussion if a certain feature should be done in Matrioska or in the app itself as it may only serve a specific purpose in an app I want to start and discuss the vision of Matrioska.

As we can then move easily decide on feature requests what goes in or what needs to be forked or done in the apps itself.

Currently in the readme:
> Matrioska lets you create your layout and define the content of your app in a simple way.

Going back to the discussion we currently have about if we should include scroling to a child in the `StackViewController` this would be a no then and done by the app itself.

cc: @ktraunmueller @joanromano @MP0w

**Comment by ChristianOrgler** [comment]
Closing statement, we decided to not put the scrolling logic nor other support which hint to features we may need in an app into Matrioska.

The lib itself should only be responsible for building the content and layout of an app.

**Comment by joanromano** [comment]
Fair enough; if anybody comes up with a good generic solution as we discussed, there's always time to reopen this thread.
