### ISSUE TITLE
Control Navigation Bar visibility

### ISSUE THREAD

**Issue by markushi** [runtastic/Matrioska#24]
At the moment the navigation bar is controlled by the navigation component. Whilst this works great most of the time, we also have some special use cases where want to hide the navigation bar or let another component control it.

The documentation changes are part of #22 
I talked to the teams who would take advantage of the `show_nav_bar` attribute: It would meet their requirements (both Android and iOS).

Comments welcome!

**Comment by mathiasAichinger** [comment]
I added a comment to the PR. Maybe discuss tomorrow again F2F to clarify the points.
