### ISSUE TITLE
Rulesets to define the visibility of a Component

### ISSUE THREAD

**Issue by MP0w** [runtastic/Matrioska#4]
We want to be able to specify visibility logic of some `Component`.
These rules can also be loaded from a JSON, given an identifier (#3).
Rules will affect the visibility of a `Component`.

Example:
If we have a `Component` with the identifier `statistics` we may want to show it only for premium users or to new users.  
The current idea is that a rule is a sort of `Wrapper`, evaluates the rules and decide to show or not its child. However we also want to be able to compose rules using `AND`, `OR` and `NOT`

`(UserIsPremium - OR - UserIsNew)  { statistics }`

A rule could be a new `Component` enum case, needs to support nesting rules and logical operators.
The rule's meta would be the child `Component`'s meta.
The rule, being a `Component` needs to be able to build a `UIViewController`; so it would evaluate the rule and returns it's child view or nil.

- [ ] JSON schema needs to support rules
- [ ] Implement rules

**Comment by joanromano** [comment]
@MP0w should therefore rules also be registered with factories, same idea as the other components?

**Comment by MP0w** [comment]
I think so because you might want to define new rules, what do you think?

**Comment by joanromano** [comment]
Yup think so too, wanted to be aligned.

**Comment by joanromano** [comment]
After discussion with @markushi we agreed on three different options for the JSON schema handling:

- The rule type is provided at the same layer as `type`, `meta` and `children`:

```
{
    "type": "tabbar",
    "meta": {
        "selected_index": 1
    },
    "children": [...],
    "rule_type": "user_is_premium"
}
```

- The rule type is an object that wraps the component:

```
{   
    "type": "user_is_premium",
    "component":  {
        "type": "tabbar",
        "meta": {
            "selected_index": 1
        },
        "children": [...]
    }
}
```

- The rule type is provided within `meta` as a new config object. This would then need a separation of the different config objects within meta:

```
{
    "type": "tabbar",
    "meta": {
        "tab_config": {
            "selected_index": 1     
        },
       "rule_config": {
            "type": "user_is_premium"       
       }
    },
    "children": [...],
}
```

I will try to approach the three of them in order to be able to have a more concrete pro/con list.

Another point that @markushi brought was the need for rules to be able to say when they should be reevaluated based on the data that they have.  e.g app gets notified from database layer by a change of user going from normal -> premium, the rule has to be then automatically reevaluated. Which possible ways would we have to achieve this?

Feel free to bring any inputs on both topics @mathiasAichinger @AndreasThenn @MP0w @bassemawny

**Comment by joanromano** [comment]
I totally forgot about representing logical rules within our JSON schema. After some research, I found a common way to handle this which is basically what's specified here:

http://jsonlogic.com/operations.html#logic-and-boolean-operations
http://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.swg.im.dbclient.json.doc/doc/r0061295.html

With this documentation in mind, our logical operations on rule types would be like this:

| Operator | Description | Example |
| --------- | ------------ | ----------- |
| `AND` | AND operation on an array with at least two rules. | `{"AND":["is_gold_member", "is_male"]}` |
| `OR` | OR operation on an array with at least two rules. | `{"OR":["is_gold_member", "is_male"]}` |
| `NOT` | NOT operation on a rule. | `{"NOT":"is_gold_member"}` |

-----

This would fit in our previous examples of the JSON schema with rules:

- The rule is provided at the same layer as `type`, `meta` and `children`:

```
{
    "type": "tabbar",
    "meta": {
        "selected_index": 1
    },
    "children": [...],
    "rule": {
        "AND": [
            "is_gold_member", 
            "is_male"
        ]
    }
}
```

- The rule type is an object that wraps the component:

```
{
    "AND": [
        "is_gold_member", 
        "is_male"
    ],
    "component":  {
        "type": "tabbar",
        "meta": {
            "selected_index": 1
        },
        "children": [...]
    }
}
```

- The rule is provided within `meta` as a new config object. This would then need a separation of the different config objects within meta:

```
{
    "type": "tabbar",
    "meta": {
        "tab_config": {
            "selected_index": 1     
        },
       "rule_config": {
           "AND": [
               "is_gold_member", 
               "is_male"
           ]
       }
    },
    "children": [...],
}
```
